[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
vault_ai = "csiotTu5ChbPzzjnpbNyWkfAQmyRNqTvLw362xUkn8y"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"