[toolchain]
anchor_version = "1.0.0"

[programs.devnet]
vault_ai = "csiotTu5ChbPzzjnpbNyWkfAQmyRNqTvLw362xUkn8y"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"
